### ISSUE TITLE
insserv: missing LSB tags and overrides

### ISSUE THREAD

**Issue by ghost** [geerlingguy/ansible-role-sonar#11]
On my sandbox Debian GNU/Linux 8.4 (jessie), I am stuck with this error message:

```
TASK [geerlingguy.sonar : Ensure Sonar is running and set to start on boot.] ***
fatal: [sandbox-sonar]: FAILED! => {"changed": false, "failed": true, "msg": "Error when trying to enable sonar: rc=1 Synchronizing state for sonar.service with sysvinit using update-rc.d...\nExecuting /usr/sbin/update-rc.d sonar defaults\ninsserv: warning: script 'sonar' missing LSB tags and overrides\nExecuting /usr/sbin/update-rc.d sonar enable\nupdate-rc.d: error: sonar Default-Start contains no runlevels, aborting.\n"}
```

this is due to the lack of the header below in the **/etc/init.d/sonar** (the script you link actually):

```
### BEGIN INIT INFO
# Provides:          scriptname
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
```

I am not quite sure of the best workaround. I prefer to insert these lines if they are missing just after the **#!/bin/bash**, instead of a replacement static file.

Source: https://wiki.debian.org/LSBInitScripts

**Comment by ghost** [comment]
This error message is very strange, it appears only at the first run. When I relaunch the ansible-playbook, no more error message.

```
TASK [geerlingguy.sonar : Ensure Sonar is running and set to start on boot.] ***
changed: [sandbox-sonar]

TASK [geerlingguy.sonar : Make sure Sonar is responding on the configured port.] ***
ok: [sandbox-sonar]
```

**Comment by geerlingguy** [comment]
This seems like an issue that should be addressed upstream: https://github.com/SonarSource/sonarqube — I haven't had time to find where the best place to track the issue would be though...

**Comment by jermon** [comment]
This happens for me too on Ubuntu Xenial. The workaround (just run again) works.

**Comment by geerlingguy** [comment]
This should be fixed by https://github.com/geerlingguy/ansible-role-sonar/pull/26 — it now includes a unit file for systemd servers that should get things started correctly on the first run. Please let me know if it doesn't work for you.
