### ISSUE TITLE
Convert to Docker tests for Travis CI

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-sonar#19]
Because running everything on Travis' default environment is getting to be annoying.

**Comment by ghost** [comment]
Nice idea. Good luck for this improvement !

By the way, maybe it can help you, this python script parses the meta/main.yml and install the dependencies:
https://github.com/olo-dw/ansible-validator/blob/master/requirements.py

Thank you for all the job you do!

**Comment by geerlingguy** [comment]
Hmm... I was approaching this as if MySQL wasn't running, but that's not actually the issue. It's just the MySQL task that's broken on Ubuntu 14.04:

```
TASK [geerlingguy.mysql : Disallow root login remotely] ************************
failed: [localhost] (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')) => {"changed": false, "cmd": ["mysql", "-NBe", "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"], "delta": "0:00:00.044375", "end": "2016-08-25 18:12:19.693479", "failed": true, "item": "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')", "rc": 1, "start": "2016-08-25 18:12:19.649104", "stderr": "ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)", "stdout": "", "stdout_lines": [], "warnings": []}
```

Going to do some testing on the MySQL role here: https://github.com/geerlingguy/ansible-role-mysql/issues/57

**Comment by geerlingguy** [comment]
Looks like it's related to an upstream Travis issue with the recent GCE outage and forced update to Docker 1.12... see comments in the issue linked in the above comment.
