### ISSUE TITLE
new LTS release available

### ISSUE THREAD

**Issue by AndreasEK** [geerlingguy/ansible-role-sonar#23]
# Default to the latest LTS release.
sonar_lte_release: "5.6.3"
sonar_download_url: https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-{{ sonar_lte_release }}.zip
sonar_version_directory: sonarqube-{{ sonar_lte_release }}

**Comment by geerlingguy** [comment]
I'm trying to get the Docker-based tests working correctly first (see https://github.com/geerlingguy/ansible-role-sonar/pull/20), but would like to update. Thanks!
