### ISSUE TITLE
default sonar download URL is invalid now, then generate invalid sonarqube-4.5.5.zip

### ISSUE THREAD

**Issue by rellaguo** [geerlingguy/ansible-role-sonar#5]
Now sonarqube dist URL http://dist.sonar.codehaus.org/ would redirect to http://downloads.sonarsource.com/sonarqube/. So http://dist.sonar.codehaus.org/sonarqube-4.5.5.zip is invalid. But ansible task still generate one sonarqube-4.5.5.zip and put it under directory /root/. Then unzip task would be failed.

TASK [geerlingguy.sonar : Unzip Sonar.] ****************************************

fatal: [target1]: FAILED! => {"changed": false, "failed": true, "msg": "Failed t
o find handler for \"/root/sonarqube-4.5.5.zip\". Make sure the required command
 to extract the file is installed.", "stat": {"exists": false}}

The error message seems that the root cause is extract command is not installed. It tricks users.

So update the variable default value is necessary.

**Comment by rellaguo** [comment]
PS, now I can use http://dist.sonar.codehaus.org/sonarqube-4.5.5.zip to download again. It seems the redirection is unstable. Maybe we still should use http://downloads.sonarsource.com/sonarqube/ by default to make this role stable.

**Comment by geerlingguy** [comment]
Thanks for noting this—I've updated the default download URL.
