### ISSUE TITLE
Sonar runs as root.

### ISSUE THREAD

**Issue by bvansomeren** [geerlingguy/ansible-role-sonar#7]
Hi,

Thanks for this role, a real timesaver.
I never run services like this as root (and it seems your other roles like Jenkins don't do this either)
I've gone ahead and forked the role, made a change and tested it locally in a feature branch.
Would you be interested in my pull request that changes this to a configurable user? Fixed by #6

**Comment by gvirtuoso** [comment]
SOLVED: 
It has worked pretty well for me.
Thanks @bvansomeren

**Comment by gvirtuoso** [comment]
@geerlingguy you definitely should take a look on this PR.
I'm using that on Ubuntu 16.04 (EC2 - ami-0f9cf087c1f27d9b1 # Ubuntu-16.04 2018-12-22) and the role has a bug without this PR.
