### ISSUE TITLE
service sonar cannot start by ansible task on CentOS 7

### ISSUE THREAD

**Issue by rellaguo** [geerlingguy/ansible-role-sonar#9]
This role works well on Debian. But on CentOS 7, failed.

TASK [geerlingguy.sonar : Ensure Sonar is running and set to start on boot.] ***
fatal: [target1]: FAILED! => {"changed": false, "failed": true, "msg": "systemd could not find the requested service \"'sonar'\": "}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @site.retry

**Comment by tillias** [comment]
Confirm for Ubuntu 16.04.1 LTS. Not working as well

**Comment by luxiconn** [comment]
I'm having the same issue with CentOS 7.3

TASK [geerlingguy.sonar : Ensure Sonar is running and set to start on boot.] ***
fatal: [target]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'sonar'\": "}

I can ssh into the server and `service sonar start` and it will start the service correctly.

**Comment by geerlingguy** [comment]
This was just fixed in https://github.com/geerlingguy/ansible-role-sonar/pull/26 — thanks for the issue report!
